<a href="https://colab.research.google.com/github/aditiR2508/Preprocessing-on-a-dataset-and-dealing-with-missing-values/blob/main/Expt12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unit 3- Data Wrangling
# Experiment-12
## To perform preprocessing on a dataset and Dealing with Missing Values
## Aditi Rathore
## 25070123006
## EnTC A1

In [ ]:
# creating database containing non-number values
import pandas as pd
import numpy as np
df = pd.DataFrame({'A':[11,21, np.nan], 'B':[15, np.nan, np.nan], 'C':[10,20,30]})
df

      A     B   C
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [ ]:
#Boolean function
df.isna ()   ##'isna' command's output is true when given number is NaN and false when it IS a number

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [ ]:
# Inverse of 'isna' command
df.notna ()

       A      B     C
0   True   True  True
1   True  False  True
2  False  False  True

In [ ]:
#columnwise na values
df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [ ]:
#NaN Rows are dropped/deleted--->complete row is removed if it contains even one NaN value
df.dropna ()

      A     B   C
0  11.0  15.0  10

In [ ]:
#To replace NaN values by given value
df.fillna(value=7.5)

      A     B   C
0  11.0  15.0  10
1  21.0   7.5  20
2   7.5   7.5  30

In [ ]:
#Mean values of columns are calculated and then replaced with all NaN values
df.fillna(df.mean())

      A     B   C
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [ ]:
#Step 1--->New dataset
import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/2023"]
}
df = pd.DataFrame(data)
df

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC     10/06/2023

In [ ]:
##saving original dataset as csv file
df.to_csv("student_data.csv", index=False)

print("\nCleaned CSV file saved as student_data.csv")

Cleaned CSV file saved as student_data.csv

In [ ]:
# Step 2--->Replacing '-' with NaN to markk missing values
df.replace("-", np.nan, inplace=True)

##Converting columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors='coerce')
df

##when converting data like strings-->datatime, if some values are invalid or cannot be converted then instead of showing an error, it will replace those invalid values with NaT(Not a Time)

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC     10/06/2023

In [ ]:
# Step 3---> Check missing values
print("\nMissing Values: ")
print()
print(df.isnull().sum())   ##identifies all null/NaN values and sums it

Missing Values:

Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [ ]:
# Step 4--> Fill missing Age and Marks with mean
df["Age"].fillna(df["Age"].mean(), inplace=True)
df
#Fill missing Marks with Median
df["Marks"].fillna(df["Marks"].median(), inplace=True)
df

/tmp/ipykernel_927/2077382997.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/tmp/ipykernel_927/2077382997.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00  85.00        CSE     2023-01-06
1      102  Rohan  20.75  90.00         IT     2023-03-06
2      103  Meera  21.00  84.75        CSE     2023-05-06
3      104  Karan  20.00  88.00        CSE     2023-07-06
4      105   Anil  22.00  76.00       E&TC            NaT

In [ ]:
# Step 5--->Fixing inconsistent text formatting
df["Department"]= df["Department"].str.upper()
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00  85.00        CSE     01-06-2023
1      102  Rohan  20.75  90.00         IT     03-06-2023
2      103  Meera  21.00  84.75        CSE     05-06-2023
3      104  Karan  20.00  88.00        CSE     07-06-2023
4      105   Anil  22.00  76.00       E&TC     10/06/2023

In [ ]:
# Step 6---> To convert admission date to standard datetime format
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00  85.00        CSE     2023-01-06
1      102  Rohan  20.75  90.00         IT     2023-03-06
2      103  Meera  21.00  84.75        CSE     2023-05-06
3      104  Karan  20.00  88.00        CSE     2023-07-06
4      105   Anil  22.00  76.00       E&TC            NaT

In [ ]:
# Step 7--->Cleaned Data
print("Cleaned Data: ")
print()
df

Cleaned Data:

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00  85.00        CSE     2023-01-06
1      102  Rohan  20.75  90.00         IT     2023-03-06
2      103  Meera  21.00  84.75        CSE     2023-05-06
3      104  Karan  20.00  88.00        CSE     2023-07-06
4      105   Anil  22.00  76.00       E&TC            NaT

In [ ]:
# Step 8---> save cleaned dataset
df.to_csv("Cleaned_student_data.csv", index=False)

print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [3]:
## New dataset
import pandas as pd
import numpy as np
df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [4]:
# Checking missing values
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [5]:
#Imputing Missing values
df["Luggage.room"].mean()

np.float64(13.890243902439025)

In [6]:
df["Luggage.room"].median()

14.0

In [7]:
df["Luggage.room"] = df["Luggage.room"].fillna(value=df["Luggage.room"].mean())
df["Rear.seat.room"]=df["Rear.seat.room"].fillna(value=df["Rear.seat.room"].mean())
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.000000
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.000000
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.000000
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.000000
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.000000
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,13.890244
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.000000
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.000000
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.000000
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.000000

In [8]:
df["AirBags"]=df["AirBags"].fillna(value=df["AirBags"].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [9]:
df.head

<bound method NDFrame.head of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25         Driver only
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17         Driver only
89   Volkswagen   Passat  Compact   20.0        21         Driver only
90   Volkswagen  Corrado   Sporty   23.3        18         Driver only
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5     11.000000
1          200           5            30.0     15.000000
2          172           5            28.0     14.000000
3          172           6            31.0     17.000000
4          208           4            27.0     13.000000
..         ...         ...             ...           ...
88         109           7            34.0     13.890244
89         134           5            31.5     14.000000
90         178           4            26.0     15.000000
91         114           5            29.5     14.000000
92         168           5            30.0     15.000000

[93 rows x 10 columns]>

In [10]:
df.tail

<bound method NDFrame.tail of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25         Driver only
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17         Driver only
89   Volkswagen   Passat  Compact   20.0        21         Driver only
90   Volkswagen  Corrado   Sporty   23.3        18         Driver only
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5     11.000000
1          200           5            30.0     15.000000
2          172           5            28.0     14.000000
3          172           6            31.0     17.000000
4          208           4            27.0     13.000000
..         ...         ...             ...           ...
88         109           7            34.0     13.890244
89         134           5            31.5     14.000000
90         178           4            26.0     15.000000
91         114           5            29.5     14.000000
92         168           5            30.0     15.000000

[93 rows x 10 columns]>